services:
  postgres:
    image: postgres:16
    container_name: cloudrower-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cloudrower
      POSTGRES_USER: cloudrower_user
      POSTGRES_PASSWORD: cloudrower_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: